animationList[]=
{
  "beacon_front_hide",1,
  "beacon_rear_hide",1,
  "LED_lights_hide",0,
  "reflective_tape_hide",1,
  "side_protective_frame_hide",0,
  "spare_tyre_hide",1,
  "spare_tyre_holder_hide",1,
  "roof_rack_hide",0,
  "ladder_hide",0,
  "front_protective_frame_hide",0,
  "rearsteps_hide",0
};
textureList[]={"Steam",1,"Swifd",0,"IdapCargo",0,"IdapTransport",0,"IdapAmbulance",0,"CivAmbulance",0,"CivService",0,"Syndikat",0,"FIA3",0,"FIA2",0,"FIA1",0,"Daltgreen",0,"Vrana",0,"BluePearl",0,"Fuel",0,"BattleBus",0,"Green",0,"Black",0,"Red",0,"Blue",0,"Orange",0,"White",0};
class textureSources
    {
      class Steam
      {
        displayName="Steam Support";
        author="Kavik";
        textures[]=
        {
          "GDF_Faction\Vehicle_Camos\Steam_Support_Van\van_body_steam_CO.paa","\a3\soft_f_orange\van_02\data\van_wheel_co.paa","a3\soft_f_orange\van_02\data\van_glass_civservice_ca.paa","GDF_Faction\Vehicle_Camos\Steam_Support_Van\van_body_steam_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_dirty.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel_dirty.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
          
        };
      };
      class IDAP
      {
        displayName="$STR_A3_CfgFactionClasses_CIV_IDAP_F0";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_IdapCargo_CO.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_wheel_dirty_CO.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_glass_dirty_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_IdapCargo_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_dirty.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel_dirty.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class Redstone
      {
        displayName="$STR_A3_CfgVehicles_Van_02_vehicle_base_F_TextureSources_Redstone0";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Redstone_CO.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_wheel_Redstone_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_glass_utility_CA.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat"
        };
        factions[]=
        {
        };
      };
      class CivService
      {
        displayName="$STR_A3_CivService1";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_CivService_CO.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_wheel_dirty_CO.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_glass_CivService_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_CivService_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\a3\Soft_F_Orange\Van_02\Data\van_wheel_dirty.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class Syndikat
      {
        displayName="$STR_A3_Syndikat0";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Syndikat_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_wheel_co.paa",
          "\a3\soft_f_orange\van_02\data\van_glass_utility_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Syndikat_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class FIA1
      {
        displayName="$STR_A3_OFFROAD_01_CIVIL_BASE_F_TEXTURESOURCES_GUERILLA_010";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_FIA_01_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_wheel_co.paa",
          "\a3\soft_f_orange\van_02\data\van_glass_utility_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_FIA_01_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class FIA2
      {
        displayName="$STR_A3_OFFROAD_01_CIVIL_BASE_F_TEXTURESOURCES_GUERILLA_020";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_FIA_02_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_wheel_co.paa",
          "\a3\soft_f_orange\van_02\data\van_glass_utility_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_FIA_02_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class FIA2U
      {
        displayName="$STR_A3_FIA2U0";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_FIA_02_unfinished_CO.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_wheel_CO.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_glass_FIA_02_unfinished_CA.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_FIAU.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Soft_F_Orange\Van_02\Data\van_glass_FIAU.rvmat"
        };
        factions[]=
        {
        };
      };
      class FIA3
      {
        displayName="$STR_A3_OFFROAD_01_CIVIL_BASE_F_TEXTURESOURCES_GUERILLA_030";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_FIA_03_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_wheel_co.paa",
          "\a3\soft_f_orange\van_02\data\van_glass_utility_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_FIA_03_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class Masked
      {
        displayName="$STR_A3_Masked0";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Masked_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_wheel_co.paa",
          "\a3\soft_f_orange\van_02\data\van_glass_utility_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Masked_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class Daltgreen
      {
        displayName="$STR_A3_Daltgreen1";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Daltgreen_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_wheel_co.paa",
          "\a3\soft_f_orange\van_02\data\van_glass_utility_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Daltgreen_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class Vrana
      {
        displayName="$STR_A3_TEXTURESOURCES_VRANA0";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Vrana_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_wheel_co.paa",
          "\a3\soft_f_orange\van_02\data\van_glass_utility_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Vrana_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class BluePearl
      {
        displayName="$STR_A3_BluePearl1";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_BluePearl_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_wheel_co.paa",
          "\a3\soft_f_orange\van_02\data\van_glass_utility_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_BluePearl_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class Fuel
      {
        displayName="$STR_A3_TEXTURESOURCES_FUEL0";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Fuel_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_wheel_co.paa",
          "\a3\soft_f_orange\van_02\data\van_glass_utility_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Fuel_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class BattleBus
      {
        displayName="";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_BB_CO.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_wheel_BB_CO.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_glass_BB_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_BB_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Building_Semafor_Green.rvmat"
        };
        factions[]=
        {
        };
      };
      class Green
      {
        displayName="$STR_A3_TEXTURESOURCES_GREEN0";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Green_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_wheel_co.paa",
          "\a3\soft_f_orange\van_02\data\van_glass_utility_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Green_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class Black
      {
        displayName="$STR_A3_TEXTURESOURCES_BLACK0";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Black_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_wheel_co.paa",
          "\a3\soft_f_orange\van_02\data\van_glass_utility_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Black_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class Red
      {
        displayName="$STR_A3_TEXTURESOURCES_RED0";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Red_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_wheel_co.paa",
          "\a3\soft_f_orange\van_02\data\van_glass_utility_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Red_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class Blue
      {
        displayName="$STR_A3_TEXTURESOURCES_BLUE0";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Blue_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_wheel_co.paa",
          "\a3\soft_f_orange\van_02\data\van_glass_utility_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Blue_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class Orange
      {
        displayName="$STR_A3_TEXTURESOURCES_ORANGE0";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Orange_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_wheel_co.paa",
          "\a3\soft_f_orange\van_02\data\van_glass_utility_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_Orange_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class White
      {
        displayName="$STR_A3_TEXTURESOURCES_WHITE0";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_White_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_wheel_co.paa",
          "\a3\soft_f_orange\van_02\data\van_glass_utility_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_White_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class Swifd
      {
        displayName="$STR_A3_TextureSources_Swifd0";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_armazon_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_wheel_co.paa",
          "\a3\soft_f_orange\van_02\data\van_glass_utility_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_armazon_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class AAN
      {
        displayName="$STR_A3_RSCDISPLAYAANARTICLE_AUTHOR";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_AAN_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_wheel_co.paa",
          "\a3\soft_f_orange\van_02\data\van_glass_utility_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_AAN_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Orange_emit.rvmat"
        };
        factions[]=
        {
        };
      };
      class Gendarmerie
      {
        displayName="$STR_A3_CfgVehicles_Offroad_01_civil_base_F_TextureSources_Gendarmerie0";
        author="$STR_A3_Bohemia_Interactive";
        textures[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body_gen_CO.paa",
          "\a3\soft_f_orange\van_02\data\van_wheel_co.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_glass_gen_CA.paa",
          "\a3\Soft_F_Orange\Van_02\Data\van_body_gen_CO.paa"
        };
        materials[]=
        {
          "\a3\Soft_F_Orange\Van_02\Data\van_body.rvmat",
          "\A3\Soft_F_Orange\Van_02\Data\van_wheel.rvmat",
          "",
          "\a3\Data_f\Lights\Car_Beacon_Blue_emit.rvmat"
        };
        factions[]=
        {
        };
      };
    };