class AnimationSources: AnimationSources
		{
			class recoil_source
			{
				source="reload";
				weapon="CMD_GDF_cannon_82mm";
			};
		};
class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class Turrets: Turrets
				{
					class CommanderOptics: CommanderOptics
					{
						commanding=2;
						body="commander_turret";
						gun="commander_gun";
						memoryPointGunnerOutOptics="commanderview";
						memoryPointGunnerOptics="commanderview";
						minElev=-15;
						maxElev=55;
						initElev=0;
						minTurn=-360;
						maxTurn=360;
						initTurn=0;
						minCamElev=-90;
						maxCamElev=90;
						weapons[]=
						{
							"Laserdesignator_mounted",
							"TKE_SmokeLauncher"
						};
						magazines[]=
						{
							"Laserbatteries",
							"TKE_3Rnd_SmokeLauncherMag"
						};
						soundServo[]=
						{
							"TKE_Kuiper_Engagements\TKE_Wheeled_C\sounds\weapons\servo",
							0.5,
							1,
							10
						};
						soundServoVertical[]=
						{
							"TKE_Kuiper_Engagements\TKE_Wheeled_C\sounds\weapons\servo",
							0.5,
							1,
							10
						};
						forceHideGunner=1;
						gunnerAction="driver_hemtt";
						gunnerInAction="Driver_APC_Wheeled_03_cannon_F_in";
						gunnerGetInAction="GetInLow";
						gunnerGetOutAction="GetOutLow";
						gunnerOpticsModel="\A3\weapons_f\reticle\Optics_Commander_02_F";
						gunnerOutOpticsModel="";
						gunnerOpticsEffect[]={};
						isPersonTurret=0;
						outGunnerMayFire=0;
						inGunnerMayFire=1;
						personTurretAction="vehicle_turnout_2";
						minOutElev=-45;
						maxOutElev=65;
						initOutElev=0;
						minOutTurn=-90;
						maxOutTurn=90;
						initOutTurn=0;
						gunnerForceOptics=1;
						class ViewGunner: ViewGunner
						{
						};
						class ViewOptics: ViewOptics
						{
							initAngleX=0;
							minAngleX=-30;
							maxAngleX=30;
							initAngleY=0;
							minAngleY=-100;
							maxAngleY=100;
							initFov=0.60000002;
							minFov=0.60000002;
							maxFov=0.60000002;
							visionMode[]=
							{
								"Normal",
								"NVG",
							};
							thermalMode[]={0,1};
						};
						class OpticsIn
						{
							class Wide: ViewOptics
							{
								initAngleX=0;
								minAngleX=-30;
								maxAngleX=30;
								initAngleY=0;
								minAngleY=-100;
								maxAngleY=100;
								initFov=0.60000002;
								minFov=0.60000002;
								maxFov=0.60000002;
								visionMode[]=
								{
									"Normal",
									"NVG",
								};
								thermalMode[]={0,1};
								gunnerOpticsModel="\A3\Weapons_F\Reticle\Optics_Commander_01_w_F.p3d";
								gunnerOpticsEffect[]={};
							};
							class Medium: Wide
							{
								gunnerOpticsModel="\A3\Weapons_F\Reticle\Optics_Commander_01_m_F.p3d";
								initFov=0.07;
								minFov=0.07;
								maxFov=0.07;
							};
							class Narrow: Wide
							{
								gunnerOpticsModel="\A3\Weapons_F\Reticle\Optics_Commander_01_n_F.p3d";
								initFov=0.028000001;
								minFov=0.028000001;
								maxFov=0.028000001;
							};
						};
						turretInfoType="RscOptics_MBT_01_commander";
						usePip=1;
						showCrewAim=1;
						startEngine=0;
						class HitPoints
						{
						};
						stabilizedInAxes=3;
						maxHorizontalRotSpeed=4;
						maxVerticalRotSpeed=4;
						gunnerHasFlares=0;
						viewGunnerInExternal=1;
					};
				};
				commanding=1;
				gunnerName="Gunner";
				weapons[]=
				{
					"CMD_GDF_cannon_82mm"
				};
				magazines[]=
				{
					"CMD_GDF_50Rnd_82mm_HEAT_T_Yellow",
          			"CMD_GDF_50Rnd_82mm_HEAT_T_Yellow",
          			"CMD_GDF_50Rnd_82mm_HEAT_T_Yellow"
				};
				minElev=-5;
				maxElev=90;
				maxHorizontalRotSpeed=0.5;
				maxVerticalRotSpeed=0.40000001;
				turretInfoType="RscOptics_crows";
				elevationMode=0;
				class OpticsIn
				{
					class Wide: ViewOptics
					{
						initAngleX=0;
						minAngleX=-30;
						maxAngleX=30;
						initAngleY=0;
						minAngleY=-100;
						maxAngleY=100;
						initFov=0.5;
						minFov=0.5;
						maxFov=0.5;
						visionMode[]=
						{
							"Normal",
							"NVG"
						};
						thermalMode[]={0,1};
						gunnerOpticsModel="\A3\Weapons_F\Reticle\Optics_Gunner_APC_01_w_F.p3d";
						gunnerOpticsEffect[]={};
					};
					class Medium: Wide
					{
						gunnerOpticsModel="\A3\Weapons_F\Reticle\Optics_Gunner_APC_01_m_F.p3d";
						initFov=0.07;
						minFov=0.07;
						maxFov=0.07;
					};
					class Narrow: Wide
					{
						gunnerOpticsModel="\A3\Weapons_F\Reticle\Optics_Gunner_APC_01_n_F.p3d";
						initFov=0.028000001;
						minFov=0.028000001;
						maxFov=0.028000001;
					};
				};
				class ViewOptics: ViewOptics
				{
					initAngleX=0;
					minAngleX=-30;
					maxAngleX=30;
					initAngleY=0;
					minAngleY=-100;
					maxAngleY=100;
					initFov=0.5;
					minFov=0.5;
					maxFov=0.5;
					visionMode[]=
					{
						"Normal",
						"NVG"
					};
					thermalMode[]={0,1};
				};
				class ViewGunner: ViewOptics
				{
					initAngleX=0;
					minAngleX=-30;
					maxAngleX=15;
					initAngleY=0;
					minAngleY=-100;
					maxAngleY=100;
					minFov=0.25;
					maxFov=1.25;
					initFov=0.75;
					visionMode[]={};
				};
			};
		};